### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by antoinerey** [insin/eslint-config-jonnybuchanan#3]
Great idea you had there ! It works like a charm, and updates are not a pain in the ass anymore.
1. Did you, by any chance, used this config with the Atom IDE's package [linter-eslint](https://github.com/AtomLinter/linter-eslint) ? I'm struggling to make it work and any help would be welcome.
2. Is there any reason you're keeping `eslint v1.x.x` ? I am asking this, because it works the same with the `v2.x.x` and maybe there is some restrictions I didn't notice.

**Comment by insin** [comment]
1. This doesn't work out of the box in linter-eslint because it goes looking for `node_modules/eslint` then runs `lib/cli.js` directly from there ([see here for impl details](https://github.com/AtomLinter/linter-eslint/blob/master/src/worker-helpers.js))
   
   The point of this config is to own all the required linting dependencies for you - under npm2 there won't be an `eslint` in your top-level `node_modules` and under npm3 it will move `eslint` up to the top level, but it won't be tied into this configration.
   
   This module provides its own `eslint` bin script (which ends up in `node_modules/.bin/eslint`) which is hard-wired to use the configuration it manages in the scope of all the necessary dependencies - this bin script is what the Sublime Text's SublimeLinter-ESLint plugin looks for and runs to perform linting.
   
   I don't know if the linter-eslint devs have an appetite to change how they look for and run ESLint, and I haven't looked into what's involved more than above as I don't use Atom, but this should give anyone who wants to go in that direction enough info to work on a PR for it.
2. Just laziness and/or lack of time (mostly the latter recently) - v3 now uses ESLint v2 :smile_cat:
